config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

resources :product_types
resources :products

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController

  def index
    @product_types = ProductType.all
  end

  def show
    @product_type = ProductType.find(params[:id])
  end

  def new
  end

  def create
    @product_type = ProductType.new(product_type_params)
    @product_type.save
    redirect_to @product_type
  end

  private
    def product_type_params
      params.require(:product_type).permit(:title, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<p class="alert alert-success">This is a home page for a new Rails App on Google Cloud Platform!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Didymos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg fsm-bg-primary">
    <a class="navbar-brand" href="#"><%=image_tag("logo_horizontal_white.png",  class: 'logo ml-5') %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-right" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
    </div>
  </nav>

  <h2 class="text-center">Didymos Geekery is under construction. <br />Something helpful for Didymos lovers is coming soon!</h2>
  <div class="container">
    <!-- Content here -->
    <%= yield %>
  </div>


  </body>
</html>

app/views/product_types/index.html.erb
<div class="row">
  <div class="col-12">
    <% @product_types.each do |product_type| %>
      <div class="card" style="width: 18rem;">
        <img src="https://materializecss.com/images/sample-1.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= product_type.title %></h5>
          <p class="card-text"><%= product_type.description %></p>
        </div>

        <div class="card-body">
          <%= link_to 'Show All', product_type_path(product_type), class: 'btn fsm-btn-accent' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/product_types/new.html.erb
<h1>New Product Type</h1>


<%= form_with scope: :product_type, url: product_types_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/product_types/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product_type.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @product_type.description %>
</p>